" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2002 Sep 19
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings.
if v:progname =~? "evim"
  finish
endif

" Use Vim settings, rather then Vi settings (much better!).
" This must be first, because it changes other options as a side effect.
set nocompatible

" allow backspacing over everything in insert mode
set backspace=indent,eol,start

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file
endif
set history=50		" keep 50 lines of command line history
set ruler		" show the cursor position all the time
set showcmd		" display incomplete commands
set incsearch		" do incremental searching
set encoding=utf-8

" For Win32 GUI: remove 't' flag from 'guioptions': no tearoff menu entries
" let &guioptions = substitute(&guioptions, "t", "", "g")

" Don't use Ex mode, use Q for formatting
map Q gq

" This is an alternative that also works in block mode, but the deleted
" text is lost and it only works for putting the current register.
"vnoremap p "_dp

" Switch syntax highlighting on, when the terminal has colors
" Also switch on highlighting the last used search pattern.
" set language = zh_cn
if &t_Co > 2 || has("gui_running")
  syntax on
  set hlsearch
  set guifont=Consolas\ 10
endif

set sw=4
set smarttab
set ic
set number
nmap <F9> :set invhls<CR>

" Only do this part when compiled with support for autocommands.
if has("autocmd")

  " Enable file type detection.
  " Use the default filetype settings, so that mail gets 'tw' set to 72,
  " 'cindent' is on in C files, etc.
  " Also load indent files, to automatically do language-dependent indenting.
  filetype plugin indent on

  " Put these in an autocmd group, so that we can delete them easily.
  augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78

  " When editing a file, always jump to the last known cursor position.
  " Don't do it when the position is invalid or when inside an event handler
  " (happens when dropping a file on gvim).
  autocmd BufReadPost *
    \ if line("'\"") > 0 && line("'\"") <= line("$") |
    \   exe "normal g`\"" |
    \ endif
  "for c, c++
  autocmd FileType c,cpp nmap <F5> :w<cr>:make<cr>

  "for python
  autocmd BufNewFile *.py 0r ~/.vim/skeleton/skeleton.py
  autocmd FileType python setlocal et | setlocal sta | setlocal sw=4 | setlocal nowrap | setlocal go+=b
  autocmd FileType python set makeprg=python\ -c\ \"import\ py_compile,sys;\ sys.stderr=sys.stdout;\ py_compile.compile(r'%')\" 
  autocmd FileType python set efm=%C\ %.%#,%A\ \ File\ \"%f\"\\,\ line\ %l%.%#,%Z%[%^\ ]%\\@=%m 
  autocmd FileType python nmap <F5> :w<cr>:!python %<cr>
  "use python.vim
  autocmd FileType python source ~/.vim/scripts/python.vim

  "for ruby
  autocmd BufNewFile *.rb 0r ~/.vim/skeleton/skeleton.rb
  autocmd FileType ruby nmap <F5> :w<cr>:!ruby %<cr>
  autocmd BufRead *.rhtml source ~/.vim/scripts/eruby.vim | setlocal encoding=utf-8
  autocmd FileType html setlocal encoding=utf-8

  

  augroup END

else

  set autoindent		" always set autoindenting on

endif " has("autocmd")

"tags
set tags+=/vobs/ezx_apps/code/messaging/tags
set tags+=/vobs/ezx_apps/code/mystuff/tags
set tags+=/vobs/ezx_apps/code/share/tags
set tags+=/vobs/ezx_apps/code/utility/tags
set tags+=/vobs/ezx_apps/code/utilsdk/tags
set tags+=/vobs/ezx_apps/code/appbase/tags
set tags+=/vobs/ezx_apps/code/appsdk/tags
set tags+=/vobs/ezx_apps/code/setup/tags
set tags+=/vobs/ezx_apps/code/pim/tags
set tags+=/vobs/ezx_apps/code/am/tags
set tags+=/vobs/ezx_apps/code/flash_svg/tags
set tags+=/vobs/ezx_apps/code/mediaplayer/tags
set tags+=/vobs/ezx_apps/code/drm/tags
set tags+=/vobs/ezx_apps/code/am/tags
set tags+=/vobs/ezx_apps/code/appbase/tags
set tags+=/vobs/ezx_apps/code/textinput/tags
set tags+=/vobs/jem/caf/svgsmil/tags
set tags+=/vobs/ezx_api/code/tapi/tags
set tags+=/vobs/wsd_tapi/tags
set tags+=/vobs/linuxjava/messaging/messaging/tags
set tags+=/vobs/linuxjava/ui_framework/tags
