######################################################################
# Automatically generated by qmake (1.07a) Tue Jul 17 17:59:01 2007
######################################################################

TEMPLATE = app
CONFIG = warn_on debug
INCLUDEPATH += .

# Input
SOURCES += main.cpp \
	   util.c \
	   util1.cpp \
	   String.cpp

HEADERS += util.h \
	   util1.h \
	   String.h

debug {
    TARGET = testd
}
release {
    TARGET = test
}
